#Application
spring:
  application:
    name: ssc-asu-gender
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MYSQL
  #Cache
  cache:
    jcache:
      config: classpath:ehcache.xml
#General configuration
server:
  port: 8081
  servlet:
    context-path: /asu/v1/gender
#Logging
#logging:
#  level:
#    root: DEBUG
#Exceptions
gender:
  success: The operation was successful.
  prefix: 'API-GN:'
  error:
    general: There was an unexpected error. Please try again.

